# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified_date',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
