# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Testo')),
                ('author', models.CharField(max_length=200, verbose_name='Autore')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
